default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  password:

development:
  <<: *default
  host: localhost
  database: scraper_development
  username: dimargb

test:
  <<: *default
  host: localhost
  database: scraper_test
  username: dimargb

production:
  <<: *default
  database: sd_scraper_production
  username: sd_scraper
